"""Shared utilities for Topic 17 ingestion trust pipelines."""

from .core import (
    WinnerStyleConfig,
    build_run_metadata,
    save_json,
    sha256_file,
    detect_dataset_mode,
    generate_synthetic_click_fraud,
    load_dataset_with_fallback,
    make_small_sample,
    canonical_json,
    hash_record,
    build_merkle_root,
    append_audit_batch,
    verify_audit_log,
    tamper_log_copy,
    train_and_evaluate_models,
    train_lightgbm_bagging,
)

from .winner_style import (
    TrackMode,
    add_count_unique_cum_features,
    add_delta_time_features,
    build_competition_like_splits,
    build_rate_features_train_only,
    build_temporal_splits,
    load_talkingdata_frame,
    make_bag_subsample_indices,
    validate_split_integrity,
)

from .spark_utils import (
    create_spark_session,
    get_event_schema,
    apply_schema_casting,
    feature_engineering,
    build_baseline_stats,
    compute_drift_metrics,
    run_veracity_checks,
    compute_veracity_score,
)

__all__ = [
    "build_run_metadata",
    "WinnerStyleConfig",
    "save_json",
    "sha256_file",
    "detect_dataset_mode",
    "generate_synthetic_click_fraud",
    "load_dataset_with_fallback",
    "make_small_sample",
    "canonical_json",
    "hash_record",
    "build_merkle_root",
    "append_audit_batch",
    "verify_audit_log",
    "tamper_log_copy",
    "train_and_evaluate_models",
    "train_lightgbm_bagging",
    "TrackMode",
    "load_talkingdata_frame",
    "build_temporal_splits",
    "build_competition_like_splits",
    "add_count_unique_cum_features",
    "add_delta_time_features",
    "build_rate_features_train_only",
    "make_bag_subsample_indices",
    "validate_split_integrity",
    "create_spark_session",
    "get_event_schema",
    "apply_schema_casting",
    "feature_engineering",
    "build_baseline_stats",
    "compute_drift_metrics",
    "run_veracity_checks",
    "compute_veracity_score",
]
